### ISSUE TITLE
Something wrong with the implementation of CELF

### ISSUE THREAD

**Issue by fadingecho** [gepperho/InfluenceMaximizationBenchmarker#1]
https://github.com/gepperho/InfluenceMaximizationBenchmarker/blob/af3a53fff4a745e0b761ec4dba1327cad5ea5f79/src/solver/CelfGreedy.cpp#L59

I think the right version should look something like the following lines, because the output of the current implementation of CELF is obviously wrong, or maybe I've got something wrong.
` 
spread_[top_node] = evaluateSpread(seed_set) - current_seed_set_spread;// add the top_node to the seed set for now 
`

**Comment by gepperho** [comment]
Hello,
you are absolutely right. Thanks for pointing it out.
I just pushed a fix (d90db8d591b6507be4bdcf7ae119e23c71c89318) which should solve the issue.
